CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(20) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS match_history (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  match_id VARCHAR(64) NOT NULL UNIQUE,
  player1_id INT UNSIGNED NOT NULL,
  player2_id INT UNSIGNED NOT NULL,
  winner_id INT UNSIGNED NULL,
  player1_name VARCHAR(20) NOT NULL,
  player2_name VARCHAR(20) NOT NULL,
  winner_name VARCHAR(20) NULL,
  end_reason ENUM('WIN', 'ABORTED', 'DRAW') NOT NULL,
  score1 INT UNSIGNED NOT NULL DEFAULT 0,
  score2 INT UNSIGNED NOT NULL DEFAULT 0,
  started_at DATETIME NOT NULL,
  ended_at DATETIME NOT NULL,
  duration_sec INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_match_started_at (started_at),
  INDEX idx_match_player1 (player1_id),
  INDEX idx_match_player2 (player2_id),
  CONSTRAINT fk_match_player1 FOREIGN KEY (player1_id) REFERENCES users(id),
  CONSTRAINT fk_match_player2 FOREIGN KEY (player2_id) REFERENCES users(id),
  CONSTRAINT fk_match_winner FOREIGN KEY (winner_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ranking (
  user_id INT UNSIGNED PRIMARY KEY,
  username VARCHAR(20) NOT NULL,
  rating INT NOT NULL DEFAULT 1000,
  matches_played INT UNSIGNED NOT NULL DEFAULT 0,
  matches_won INT UNSIGNED NOT NULL DEFAULT 0,
  last_played_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ranking_rating (rating DESC),
  CONSTRAINT fk_ranking_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
